### ISSUE TITLE
Home widget with battery 🔋

### ISSUE THREAD

**Issue by person10301** [TheLastGimbus/FreeBuddy#8]
I would like to see a transparent widget showing the headphone charge

**Comment by TheLastGimbus** [comment]
Yasss - everyone's asking for it, and it's currently on top of my todo list - I'll keep updates here!

**Comment by TheLastGimbus** [comment]
Check out this nightly build: https://github.com/TheLastGimbus/FreeBuddy/actions/runs/6241769750 :fire:

**Comment by TheLastGimbus** [comment]
# :wink:
